created: 2023-08-17T20:58:54.225Z
creator:
  id: 36a2a6f5-e655-4ca9-a61d-f09377537b03
  name: Levon Arakeylan
deletedAt: null
deployedAt: null
deployedCommitId: null
folderId: null
id: 91e1dc60-0057-48eb-b9c9-fa9a3323fd61
isDeployed: false
isEditable: true
isPublic: false
name: Levon's Mighty App
organizationId: 0d9f3124-99f2-453f-bea0-c7de164915df
pages:
  - id: 4eedd23f-1cdf-4e99-96c4-4479d65dd583
    isDefault: true
settings:
  profiles:
    deployed:
      availableProfileIds:
        - d35036ef-fee0-4995-849f-a3bd8b95a5cf
        - ee036c4f-fc1f-4bd4-b000-6ccbe187a923
      defaultProfileId: d35036ef-fee0-4995-849f-a3bd8b95a5cf
    editor:
      availableProfileIds:
        - d35036ef-fee0-4995-849f-a3bd8b95a5cf
        - ee036c4f-fc1f-4bd4-b000-6ccbe187a923
      defaultProfileId: ee036c4f-fc1f-4bd4-b000-6ccbe187a923
    preview:
      availableProfileIds:
        - d35036ef-fee0-4995-849f-a3bd8b95a5cf
        - ee036c4f-fc1f-4bd4-b000-6ccbe187a923
      defaultProfileId: ee036c4f-fc1f-4bd4-b000-6ccbe187a923
updated: 2023-08-17T20:58:54.225Z
userPermissions:
  - manage:applications
  - read:applications
  - publish:applications
  - makePublic:applications
